name: Build NVIDIA drivers

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      nvidia-version:
        description: NVIDIA Driver
        type: string
        required: false
      nvidia-type:
        description: Release type
        type: choice
        options:
          - Production
          - Beta
          - Legacy

permissions:
  id-token: write
  contents: write
  attestations: write
  packages: write

concurrency:
  group: nvidia-driver-${{ github.event.inputs.nvidia-version || github.ref }}
  cancel-in-progress: true

jobs:
  build_kernel:
    environment: prod
    strategy:
      fail-fast: false
      matrix:
        arch: ["x86_64", "aarch64"]
        fedora_version: ["43"]
    runs-on: ${{ matrix.arch == 'aarch64' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build Nvidia driver
        id: build
        run: |
          if [ "${{ matrix.arch }}" == "aarch64" ]; then
              export BUILD_ARM=true
          fi
          VERSION="${{ github.event.inputs.nvidia-version }}" \
            FEDORA_VERSION="${{ matrix.fedora_version }}" ./build.sh
          echo "version=$(cat .driver-version)" >> $GITHUB_OUTPUT
      
      - name: Build OCI image with drivers
        id: oci
        run: |
            FEDORA_VERSION="${{ matrix.fedora_version }}" buildah unshare ./oci.sh
            echo "digest=$(cat ./oci-digest)" >> $GITHUB_OUTPUT
      
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-digest: "${{ steps.oci.outputs.digest }}"
          subject-name: "ghcr.io/${{ github.repository_owner }}/${{ github.repository }}"
          push-to-registry: true

      - name: Upload OCI image to Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin
          podman push localhost/nvidia-oci-${{ matrix.fedora_version}} \
            "docker://ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ steps.build.outputs.version }}-f${{ matrix.fedora_version }}"